#!/bin/sh

set -e

die() {
	echo "$@" 1>&2
	exit 1
}

mail=0

while getopts ":t:m:M" opt; do
	case $opt in
		t ) title=$OPTARG;;
		m ) message=$OPTARG;;
		M ) mail=1;;
		: ) echo "-$OPTARG requires an argument" >&2; exit 1;;
		\?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
	esac
done

shift $((OPTIND - 1))

startepoch=$(date +%s)

set +e
"$@"
rc=$?
set -e

endepoch=$(date +%s)
elapsed=$((endepoch - startepoch))

if [ $elapsed -gt 3600 ]; then
	duration="$((elapsed/3600))h $(((elapsed%3600)/60))m"
elif [ $elapsed -gt 60 ]; then
	duration="$((elapsed/60))m $((elapsed%60))s"
else
	duration="${elapsed}s"
fi

if [ "$1" != "" ]; then
	if [ "$title" = "" ]; then
		if [ $rc -gt 0 ]; then
			title="Command failed"
		else
			title="Command finished"
		fi
		title="$title on $(hostname -s)"
	fi
	if [ "$message" = "" ]; then
		cmd="$*"
		message="Command '$(echo "$cmd" | cut -c1-32)' exited"
		if [ $rc -gt 0 ]; then
			message="$message with RC $rc"
		fi
		message="$message in $duration"
	fi
fi

if [ "$title" = "" ]; then
	title="ntfy called"
fi
if [ "$message" = "" ]; then
	message="ntfy called"
fi

pushover() {
	curl -sS \
		--form-string "token=$(awk -F "=" '/token/ {print $2}' ~/.ntfy)" \
		--form-string "user=$(awk -F "=" '/user/ {print $2}' ~/.ntfy)" \
		--form-string "title=$1" \
		--form-string "message=$2" \
		https://api.pushover.net/1/messages.json \
		1>/dev/null
}

bell() {
	printf '\a'
}

tmuxmsg() {
	[ -z "$TMUX" ] || tmux display-message "$1: $2"
}

email() {
	command -v mail >/dev/null 2>&1 || die "Can't find 'mail' command"

	recipient=$(awk -F "=" '/mail_recipient/ {print $2}' ~/.ntfy)
	[ -z "$recipient" ] && die 'Missing recipient in ~/.ntfy'

	echo "$2" | mail -s "$1" "$recipient"
}

pushover "$title" "$message"
bell
tmuxmsg "$title" "$message"
[ $mail -eq 1 ] && email "$title" "$message"
