#!/bin/sh

set -e

while getopts ":t:m:" opt; do
	case $opt in
		t)
			title=$OPTARG
			;;
		m)
			message=$OPTARG
			;;
		:)
			echo "-$OPTARG requires an argument" >&2
			exit 1
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
	esac
done

shift $(($OPTIND - 1))

startepoch=$(date +%s)

set +e
"$@"
rc=$?
set -e

endepoch=$(date +%s)
elapsed=$(($endepoch - $startepoch))

if [ $elapsed -gt 3600 ]; then
	duration="$(($elapsed/3600)) h $((($elapsed%3600)/60)) m"
elif [ $elapsed -gt 60 ]; then
	duration="$(($elapsed/60)) m $(($elapsed%60)) s"
else
	duration="$elapsed s"
fi

if [ "$1" != "" ]; then
	if [ "$title" = "" ]; then
		if [ $rc -gt 0 ]; then
			title="Command failed"
		else
			title="Command finished"
		fi
	fi
	if [ "$message" = "" ]; then
		message="Command $1 exited"
		if [ $rc -gt 0 ]; then
			message="$message with RC $rc"
		fi
		message="$message in $duration"
	fi
fi

if [ "$title" = "" ]; then
	title="ntfy called"
fi
if [ "$message" = "" ]; then
	message="ntfy called"
fi

curl -s \
  --form-string "token=$(awk -F "=" '/token/ {print $2}' ~/.ntfy)" \
  --form-string "user=$(awk -F "=" '/user/ {print $2}' ~/.ntfy)" \
  --form-string "title=$title" \
  --form-string "message=$message" \
  https://api.pushover.net/1/messages.json
